### PR TITLE
Add copy to clipboard button to code blocks

### PR DESCRIPTION
**Pull request by timwis**
Implements #52 

Demo at http://timwis.github.io/patterns

Note I had to use javascript to get around zenorocha/clipboard.js#17. Once they resolve the bug, we should be able to just initialize via `new Clipboard('.copy')` and rely on the `data-clipboard-target` attributes to get the right text.

### CODE REVIEW

**Comment by zenorocha** [comment]
[v1.4.2](https://github.com/zenorocha/clipboard.js/releases/tag/v1.4.2) should fix that ;)

**Comment by timwis** [comment]
Updated - working great! Much cleaner now. Thanks @zenorocha!

**Comment by zenorocha** [comment]
lol

**Comment by karissademi** [comment]
This is awesome. Thanks!

**Comment by zenorocha** [comment]
Added to https://github.com/zenorocha/clipboard.js/wiki ;)

**Pull request merged**
