### PR TITLE
Add tel: link. #10

### PR DESCRIPTION
**Pull request by gsf**
Like so, @davewalk?

### CODE REVIEW

**Comment by davewalk** [comment]
Looks like that'll do it!

**Comment by gsf** [comment]
What do you think, @kdemi? Do we need to add any new styling for these links?

**Comment by kdemi** [comment]
Added styles to hide the link functionality on desktop, so the link won't appear to be broken when clicked on in certain browsers.

**Comment by gsf** [comment]
:+1:

**Comment by davewalk** [comment]
Cool, thx! :100:

**Pull request merged**
